# Generated by Django 4.2.5 on 2023-10-05 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120, verbose_name='Tipo de contacto')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone', models.CharField(max_length=8, validators=[django.core.validators.validate_integer], verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('web', models.URLField(verbose_name='Sitio Web')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('location', models.CharField(max_length=300, verbose_name='Ubicación')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('end_date', models.DateField(verbose_name='Fecha fin')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de fin')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Foto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Fecha y hora')),
                ('location', models.TextField(verbose_name='Lugar')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(max_length=8, verbose_name='Código postal')),
                ('dni', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.validate_integer], verbose_name='Carnet de id')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.SmallIntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')], verbose_name='Género')),
                ('phone', models.CharField(max_length=8, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('email_confirm', models.EmailField(max_length=254, verbose_name='Correo Confirmación')),
                ('average_time', models.PositiveSmallIntegerField(choices=[(1, 'Menos de 3h'), (2, 'Entre 3h y 3h15'), (3, 'Entre 3h15 y 3h30'), (4, 'Entre 3h30 y 3h45'), (5, 'Entre 3h45 y 4h'), (6, 'Más de 4h')], verbose_name='Tiempo estimado')),
                ('race_rules', models.BooleanField(default=False, verbose_name='Reglamento de la carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
