# Generated by Django 4.2.5 on 2023-10-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainformation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='extrainformation',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='extrainformation',
            name='end_date',
            field=models.DateTimeField(verbose_name='Fecha fin'),
        ),
        migrations.AlterField(
            model_name='extrainformation',
            name='start_date',
            field=models.DateTimeField(verbose_name='Fecha inicio'),
        ),
    ]
