# Generated by Django 4.2.5 on 2023-10-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_extrainformation_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='dni',
            field=models.CharField(max_length=11, verbose_name='Carnet de id'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='email_confirm',
            field=models.EmailField(max_length=254, verbose_name='Confirmación de correo'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='postal_code',
            field=models.CharField(max_length=5, verbose_name='Código postal'),
        ),
    ]
