# Generated by Django 4.2.5 on 2023-10-12 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_inscription_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aprobada'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='dni',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.validate_integer], verbose_name='Carnet de id'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='phone',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.validate_integer], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.validate_integer], verbose_name='Código postal'),
        ),
    ]
